spring.application.name=gestion-salles
spring.main.web-application-type=none
spring.main.banner-mode=off

spring.datasource.url=jdbc:postgresql://localhost:5432/classe
spring.datasource.username=postgres
spring.datasource.password=Antonio0108Andria
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework=WARN
logging.level.com.zaxxer.hikari=WARN
